% File              : compile_mfcl.m
% Author            : Pradeep Rajendran <pradeepr.roboticist@gmail.com>
% Date              : 06.24.2019
% Last Modified Date: 06.24.2019
% Last Modified By  : Pradeep Rajendran <pradeepr.roboticist@gmail.com>

% Dynamically linked libraries may need to be set for dynamically linked libraries to work.
% #!/bin/bash
% LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
% LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu \

% We just use static linking here
mex -R2018a ...
    -DFCL_NEW ...
    -output fcl_collision_checker_interface_fcl_new ...
    -v CXXFLAGS='-fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++14' ...
    -I./ ...
    -I/usr/include/eigen3 ...
    -I../MOctomap/octomap/octomap/include ...
    -I./fcl_new/fcl/build/install/include ...
    -L../MOctomap/octomap/lib/  ...
    -L./fcl_new/fcl/build/install/lib/ ...
    fcl_collision_checker_interface.cpp ...
    ./fcl_new/fcl/build/lib/libfcl.a ...
    ../MOctomap/octomap/lib/liboctomath.a ...
    ../MOctomap/octomap/lib/liboctomap.a ...
    /usr/lib/x86_64-linux-gnu/libccd.so

mex -R2018a ...
    -DFCL_OLD ...
    -output fcl_collision_checker_interface_fcl_old ...
    -v CXXFLAGS='-fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++14' ...
    -I./ ...
    -I/usr/include/eigen3 ...
    -I../MOctomap/octomap/octomap/include ...
    -I./fcl_old/fcl/build/install/include ...
    -L../MOctomap/octomap/lib/  ...
    -L./fcl_old/fcl/build/install/lib/ ...
    fcl_collision_checker_interface.cpp ...
    ./fcl_old/fcl/build/lib/libfcl.a ...
    ../MOctomap/octomap/lib/liboctomath.a ...
    ../MOctomap/octomap/lib/liboctomap.a ...
    /usr/lib/x86_64-linux-gnu/libccd.so