% File              : compile_mfcl.m
% Author            : Pradeep Rajendran <pradeepr.roboticist@gmail.com>
% Date              : 06.24.2019
% Last Modified Date: 06.24.2019
% Last Modified By  : Pradeep Rajendran <pradeepr.roboticist@gmail.com>

% Dynamically linked libraries may need to be set for dynamically linked libraries to work.
% #!/bin/bash
% LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
% LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu \

% We just use static linking here

warning('Ensure fcl_old and fcl_new are built by running the script "prep_dependencies.sh"');

mex -R2018a ...
    -DFCL_NEW ...
    -output fcl_collision_checker_interface_fcl_new ...
    -v CXXFLAGS='-fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++14' ...
    -I./include/matlab_class_interface ...
    -I./include ...
    -I/usr/include/eigen3 ...
    -I./dependencies/octomap/octomap/build/install/include ...
    -I./dependencies/fcl_new/fcl/build/install/include ...
    -L./dependencies/octomap/octomap/build/install/lib ...
    -L./dependencies/fcl_new/fcl/build/install/lib/ ...
    ./src/fcl_collision_checker_interface.cpp ...
    ./dependencies/fcl_new/fcl/build/lib/libfcl.a ...
    ./dependencies/octomap/octomap/build/install/lib/liboctomath.a ...
    ./dependencies/octomap/octomap/build/install/lib/liboctomap.a ...
    /usr/lib/x86_64-linux-gnu/libccd.so

mex -R2018a ...
    -DFCL_OLD ...
    -output fcl_collision_checker_interface_fcl_old ...
    -v CXXFLAGS='-fexceptions -fPIC -fno-omit-frame-pointer -pthread -std=c++14' ...
    -I./include/matlab_class_interface ...
    -I./include ...
    -I/usr/include/eigen3 ...
    -I./dependencies/octomap/octomap/build/install/include ...
    -I./dependencies/fcl_old/fcl/build/install/include ...
    -L./dependencies/octomap/octomap/build/install/lib ...
    -L./dependencies/fcl_old/fcl/build/install/lib/ ...
    ./src/fcl_collision_checker_interface.cpp ...
    ./dependencies/fcl_old/fcl/build/lib/libfcl.a ...
    ./dependencies/octomap/octomap/build/install/lib/liboctomath.a ...
    ./dependencies/octomap/octomap/build/install/lib/liboctomap.a ...
    /usr/lib/x86_64-linux-gnu/libccd.so